//
//  PreviewData.swift
//  MYPlanner
//
//  SwiftUI Preview 및 개발용 Mock 데이터
//  SwiftData ModelContainer를 사용하여 Preview 지원
//

import Foundation
import SwiftData

@MainActor
enum PreviewData {

    // MARK: - Model Container for Previews

    /// Preview용 ModelContainer (샘플 데이터 포함)
    static var container: ModelContainer = {
        let schema = Schema([Schedule.self, Expression.self])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)

        do {
            let container = try ModelContainer(for: schema, configurations: [config])

            // Insert sample data
            insertSampleData(into: container.mainContext)

            return container
        } catch {
            fatalError("Failed to create preview container: \(error)")
        }
    }()

    /// 빈 Preview용 ModelContainer
    static var emptyContainer: ModelContainer = {
        let schema = Schema([Schedule.self, Expression.self])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)

        do {
            return try ModelContainer(for: schema, configurations: [config])
        } catch {
            fatalError("Failed to create empty preview container: \(error)")
        }
    }()

    // MARK: - Sample Data Insertion

    private static func insertSampleData(into context: ModelContext) {
        // Create expressions (accent auto-generated by AccentFormatter)
        let expr1 = Expression(
            english: "Prepare for the product meeting."
        )
        let expr2 = Expression(
            english: "This is an important presentation."
        )
        let expr3 = Expression(
            english: "Prepare materials for the presentation."
        )
        let expr4 = Expression(
            english: "I need to fix my car.",
            isPracticed: true
        )
        let expr5 = Expression(
            english: "Take the car to the mechanic."
        )
        let expr6 = Expression(
            english: "I'm cooking dinner tonight."
        )

        // Create schedules with expressions
        let schedule1 = Schedule(
            title: "회의 준비하기",
            date: Date(),
            category: .meeting,
            expressions: [expr1, expr2, expr3]
        )

        let schedule2 = Schedule(
            title: "자동차 수리",
            date: Date(),
            category: .personal,
            expressions: [expr4, expr5]
        )

        let schedule3 = Schedule(
            title: "저녁 준비하기",
            date: Date(),
            category: .personal,
            expressions: [expr6]
        )

        let schedule4 = Schedule(
            title: "프로젝트 리뷰",
            date: Calendar.current.date(byAdding: .day, value: 1, to: Date())!,
            category: .work,
            expressions: []
        )

        let schedule5 = Schedule(
            title: "건강검진",
            date: Calendar.current.date(byAdding: .day, value: 2, to: Date())!,
            category: .health,
            expressions: []
        )

        // Insert into context
        context.insert(schedule1)
        context.insert(schedule2)
        context.insert(schedule3)
        context.insert(schedule4)
        context.insert(schedule5)
    }

    // MARK: - Single Items for Preview

    /// Preview용 단일 Schedule
    static var singleSchedule: Schedule {
        let expr1 = Expression(
            english: "Prepare for the product meeting."
        )
        let expr2 = Expression(
            english: "This is an important presentation."
        )

        return Schedule(
            title: "회의 준비하기",
            date: Date(),
            category: .meeting,
            expressions: [expr1, expr2]
        )
    }

    /// Preview용 단일 Expression (부강세 포함 단어: important)
    static var singleExpression: Expression {
        Expression(
            english: "This is an important presentation."
        )
    }
}
